name: My simple work
on:
  push:
    branches:
      - master
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Exec Script
      run: sh -c "./alert-security.sh "
